name: Build Test2

on:
  push:
    branches: [ dev, feature/* ]
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew


      - name: Build project with Gradle
        run: ./gradlew build